apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-management-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-management-service
  template:
    metadata:
      labels:
        app: catalog-management-service
    spec:
      containers:
        - name: catalog-management-service
          image: laerkeimeland/catalog-management-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq.default.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
