apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-management-service
  template:
    metadata:
      labels:
        app: inventory-management-service
    spec:
      containers:
        - name: inventory-management-service
          image: laerkeimeland/inventory-management-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80