apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-management-service
  template:
    metadata:
      labels:
        app: order-management-service
    spec:
      containers:
        - name: order-management-service
          image: laerkeimeland/order-management-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80